#!/bin/bash
# Put a named Cloudflare tunnel and an Access policy in front of mobile-tty.
#
# Why this rather than ttyd's own --password: ttyd rejects the WebSocket upgrade
# unless the request carries a basic-auth header, and Safari does not put one on
# a WebSocket handshake (tsl0922/ttyd#1437). Access authenticates with a cookie,
# and cookies *are* sent on WebSocket handshakes — so ttyd runs with no auth of
# its own and the edge does the work.
set -euo pipefail

die() { echo "cf-access: $*" >&2; exit 1; }

cd "$(dirname "$0")/.."

hostname="${1:-}"
tunnel="${2:-mobile-tty}"
port="${MTTY_PORT:-7681}"
config="$PWD/cloudflared.yml"

if [[ -z "$hostname" ]]; then
  cat <<'USAGE' >&2
Usage: scripts/cf-access.sh <hostname> [tunnel-name]

  hostname     the name to serve on, on a domain already in your Cloudflare
               account, e.g. tty.example.com
  tunnel-name  defaults to mobile-tty

First time only, in your own shell (it opens a browser):

  cloudflared tunnel login

To have this create the Access policy too, export a token with
Account > Access: Apps and Policies > Edit, and your account id:

  export CF_API_TOKEN=...  CF_ACCOUNT_ID=...  CF_ACCESS_EMAIL=you@example.com
USAGE
  exit 2
fi

[[ -f "$HOME/.cloudflared/cert.pem" ]] || {
  echo "Not logged in. Run:  cloudflared tunnel login" >&2
  exit 1
}

# Idempotent: reuse the tunnel if it is already there. Parsed rather than
# grepped, because cloudflared's JSON spacing is not ours to rely on.
tunnel_id() {
  # The name goes in as an argument, not interpolated into the program text: a
  # quote in a tunnel name would otherwise rewrite this script's source.
  cloudflared tunnel list --output json 2>/dev/null |
    python3 -c "import json,sys; print(next((t['id'] for t in json.load(sys.stdin) if t['name']==sys.argv[1]), ''))" "$tunnel"
}

id=$(tunnel_id)
if [[ -n "$id" ]]; then
  echo "reusing tunnel '$tunnel' ($id)"
else
  cloudflared tunnel create "$tunnel"
  id=$(tunnel_id)
  [[ -n "$id" ]] || { echo "could not find tunnel '$tunnel' after creating it" >&2; exit 1; }
fi

cloudflared tunnel route dns --overwrite-dns "$tunnel" "$hostname"

cat > "$config" <<YAML
# Generated by scripts/cf-access.sh. The port below is the one it was set up
# with: serving on a different --port means the tunnel points at nothing.
# `mobile-tty doctor` says so if they drift apart.
tunnel: $id
credentials-file: $HOME/.cloudflared/$id.json

ingress:
  - hostname: $hostname
    service: http://127.0.0.1:$port
  - service: http_status:404
YAML
echo "wrote $config"

# The account id is already in the login certificate, so only the token and the
# email address have to be supplied by hand.
if [[ -z "${CF_ACCOUNT_ID:-}" ]]; then
  CF_ACCOUNT_ID=$(python3 -c 'import base64, json, os, re, sys; raw = open(os.path.expanduser("~/.cloudflared/cert.pem")).read(); m = re.search(r"ARGO TUNNEL TOKEN-----(.+?)-----END", raw, re.S); sys.stdout.write(json.loads(base64.b64decode(re.sub(r"\s", "", m.group(1)))).get("accountID", "") if m else "")' 2>/dev/null) || true
fi

if [[ -n "${CF_API_TOKEN:-}" && -n "${CF_ACCOUNT_ID:-}" && -n "${CF_ACCESS_EMAIL:-}" ]]; then
  api="https://api.cloudflare.com/client/v4/accounts/$CF_ACCOUNT_ID/access/apps"
  app=$(curl -sS -X POST "$api" \
    -H "Authorization: Bearer $CF_API_TOKEN" -H "Content-Type: application/json" \
    -d "{\"name\":\"mobile-tty\",\"domain\":\"$hostname\",\"type\":\"self_hosted\",\"session_duration\":\"720h\"}")
  # Cloudflare answers 200 with {"success": false, "errors": [...]} as readily as
  # it answers 403, so the body is what decides whether this worked.
  cf_result() {
    python3 -c "
import json, sys
try: d = json.load(sys.stdin)
except Exception: print('ERROR: could not parse the API response'); raise SystemExit(1)
if not d.get('success'):
    print('ERROR: ' + '; '.join(e.get('message', str(e)) for e in d.get('errors') or [{'message': 'unknown'}]))
    raise SystemExit(1)
print(d['result']['id'])"
  }

  app_id=$(printf '%s' "$app" | cf_result) || die "creating the Access application failed: $app_id"

  policy=$(curl -sS -X POST "$api/$app_id/policies" \
    -H "Authorization: Bearer $CF_API_TOKEN" -H "Content-Type: application/json" \
    -d "{\"name\":\"only me\",\"decision\":\"allow\",\"include\":[{\"email\":{\"email\":\"$CF_ACCESS_EMAIL\"}}]}")
  printf '%s' "$policy" | cf_result >/dev/null || {
    echo "mobile-tty: the application was created but its policy was not — $hostname is open" >&2
    exit 1
  }
  protected=yes
  echo
  echo "Done. A login now stands in front of $hostname, for $CF_ACCESS_EMAIL only."
else
  protected=no
  missing=()
  [[ -n "${CF_API_TOKEN:-}" ]]    || missing+=(CF_API_TOKEN)
  [[ -n "${CF_ACCOUNT_ID:-}" ]]   || missing+=(CF_ACCOUNT_ID)
  [[ -n "${CF_ACCESS_EMAIL:-}" ]] || missing+=(CF_ACCESS_EMAIL)

  cat <<MANUAL

  ==> NOTHING IS PROTECTING https://$hostname YET <==

  The tunnel and its DNS record exist. No login stands in front of them, so
  starting the tunnel now would give a shell on this machine to anyone who
  learns the name. Set up a login first, one of two ways.

  1. Set these and run this script again. It reuses the tunnel and adds only
     the missing login:
MANUAL
  for v in "${missing[@]}"; do
    case "$v" in
      CF_API_TOKEN) cat <<'T'

       CF_API_TOKEN     dash.cloudflare.com > My Profile > API Tokens >
                        Create Token > Custom, with the permission
                        Account > Access: Apps and Policies > Edit
T
      ;;
      CF_ACCOUNT_ID) cat <<'A'

       CF_ACCOUNT_ID    not readable from ~/.cloudflared/cert.pem; it is the
                        hex id in your Cloudflare dashboard URL
A
      ;;
      CF_ACCESS_EMAIL) cat <<'E'

       CF_ACCESS_EMAIL  the address that should receive the login code
E
      ;;
    esac
  done
  cat <<MANUAL

  2. Or once by hand: Zero Trust > Access > Applications > Add an application
     > Self-hosted, domain $hostname, then a policy of Allow / Emails / your
     address.
MANUAL
fi

cat <<NEXT

  $([[ "$protected" == yes ]] && echo "Start it, in two shells:" || echo "Once a login exists, start it in two shells:")

    ./mobile-tty --port $port            # no --password: Access is the auth
    cloudflared tunnel --config $config run $tunnel
$([[ "$protected" == yes ]] && printf '\n    then open https://%s\n' "$hostname")
NEXT
